local global = vim.g
local o = vim.opt

o.number = true
o.relativenumber = true
o.clipboard = "unnamedplus"
o.cursorline = true
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.fileencoding = "utf-8"
o.ruler = true
o.mouse = "a"
o.ttimeoutlen = 0
o.wildmenu = true
o.showcmd = true
o.inccommand = "split"
o.splitright = true
o.splitbelow = true
o.termguicolors = true
o.updatetime = 200
