local global = vim.g
local o = vim.opt

o.number = true
o.relativenumber = true
o.clipboard = "unnamedplus"
o.syntax = "on"
o.cursorline = true
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.encoding = "UTF-8"
o.ruler = true
o.mouse = "a"
o.hidden = true
o.ttimeoutlen = 0
o.wildmenu = true
o.showcmd = true
inccommand = "split"
o.splitright = true
o.splitbelow = true
o.termguicolors = true
